### ISSUE TITLE
mason make macosui_starter

### ISSUE THREAD

**Issue by yuanhoujun** [macosui/macosui_starter#2]
? App name? (macosui_starter) macos_sample
? App description? (A starter Flutter application for macOS with macos_ui) test
? Organization name? (com.example) com.example
? Use window translucency? (y/N) Yes
? Show debug label? (y/N) Yes
? Use custom system menu bar? (y/N) Yes
? Add multi-window support? (y/N) No

Unable to execute hook: /Users/ouyangfeng/.mason-cache/hosted/registry.brickhub.dev/macosui_starter_1.2.1+1/hooks/pre_gen.dart.
Error: Unable to spawn isolate: The uri provided to `Isolate.spawnUri()` does not contain a valid AOT snapshot.

**Comment by GroovinChip** [comment]
@yuanhoujun are you still experiencing this issue? If so, can you please provide which version of `mason` you are using?

**Comment by yuanhoujun** [comment]
0.1.0-dev.30

**Comment by GroovinChip** [comment]
@yuanhoujun I'm not able to reproduce this issue. If it still persists, I'd suggest filing an issue with [mason_cli](https://github.com/felangel/mason/issues) and linking to this issue here.
